name: Expo Publish
on:
  push:
    branches: [ main ]
jobs:
  expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          expo-url: ${{ secrets.EXPO_CLI_TOKEN }}
